[2025-03-23 22:38:07,237] INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.22.0.2:5000 - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:38:07,237] INFO [33mPress CTRL+C to quit[0m - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:38:07,238] INFO  * Restarting with stat - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:38:11,785] INFO Retrieving saving goal with ID: 2 - call_trace=/app/app.py L107 
[2025-03-23 22:38:11,790] INFO Saving goal with ID 2 found - call_trace=/app/app.py L120 
[2025-03-23 22:38:11,791] INFO 172.22.0.1 - - [23/Mar/2025 22:38:11] "GET /goals/{goal_id}?goal_id=2 HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:38:12,447] INFO Retrieving saving goal with ID: 2 - call_trace=/app/app.py L107 
[2025-03-23 22:38:12,448] INFO Saving goal with ID 2 found - call_trace=/app/app.py L120 
[2025-03-23 22:38:12,449] INFO 172.22.0.1 - - [23/Mar/2025 22:38:12] "GET /goals/{goal_id}?goal_id=2 HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:38:13,414] INFO Retrieving saving goal with ID: 2 - call_trace=/app/app.py L107 
[2025-03-23 22:38:13,415] INFO Saving goal with ID 2 found - call_trace=/app/app.py L120 
[2025-03-23 22:38:13,416] INFO 172.22.0.1 - - [23/Mar/2025 22:38:13] "GET /goals/{goal_id}?goal_id=2 HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:38:46,084] INFO  * Detected change in '/app/schemas/saving_goal.py', reloading - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:38:46,221] INFO  * Restarting with stat - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:38:46,982] INFO Retrieving saving goal with ID: 2 - call_trace=/app/app.py L107 
[2025-03-23 22:38:46,988] INFO Saving goal with ID 2 found - call_trace=/app/app.py L120 
[2025-03-23 22:38:46,989] INFO 172.22.0.1 - - [23/Mar/2025 22:38:46] "GET /goals/{goal_id}?goal_id=2 HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:38:48,997] INFO Retrieving saving goal with ID: 2 - call_trace=/app/app.py L107 
[2025-03-23 22:38:48,999] INFO Saving goal with ID 2 found - call_trace=/app/app.py L120 
[2025-03-23 22:38:49,000] INFO 172.22.0.1 - - [23/Mar/2025 22:38:49] "GET /goals/{goal_id}?goal_id=2 HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:39:00,031] INFO  * Detected change in '/app/schemas/saving_goal.py', reloading - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:39:00,180] INFO  * Restarting with stat - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:39:01,045] INFO Retrieving saving goal with ID: 2 - call_trace=/app/app.py L107 
[2025-03-23 22:39:01,051] INFO Saving goal with ID 2 found - call_trace=/app/app.py L120 
[2025-03-23 22:39:01,052] INFO 172.22.0.1 - - [23/Mar/2025 22:39:01] "GET /goals/{goal_id}?goal_id=2 HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:39:02,973] INFO Retrieving saving goal with ID: 2 - call_trace=/app/app.py L107 
[2025-03-23 22:39:02,974] INFO Saving goal with ID 2 found - call_trace=/app/app.py L120 
[2025-03-23 22:39:02,975] INFO 172.22.0.1 - - [23/Mar/2025 22:39:02] "GET /goals/{goal_id}?goal_id=2 HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:39:03,773] INFO Retrieving saving goal with ID: 2 - call_trace=/app/app.py L107 
[2025-03-23 22:39:03,774] INFO Saving goal with ID 2 found - call_trace=/app/app.py L120 
[2025-03-23 22:39:03,775] INFO 172.22.0.1 - - [23/Mar/2025 22:39:03] "GET /goals/{goal_id}?goal_id=2 HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:39:05,293] INFO Retrieving saving goal with ID: 2 - call_trace=/app/app.py L107 
[2025-03-23 22:39:05,294] INFO Saving goal with ID 2 found - call_trace=/app/app.py L120 
[2025-03-23 22:39:05,295] INFO 172.22.0.1 - - [23/Mar/2025 22:39:05] "GET /goals/{goal_id}?goal_id=2 HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:39:29,042] INFO  * Detected change in '/app/schemas/saving_goal.py', reloading - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:39:29,172] INFO  * Restarting with stat - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:39:30,435] INFO Retrieving saving goal with ID: 2 - call_trace=/app/app.py L107 
[2025-03-23 22:39:30,440] INFO Saving goal with ID 2 found - call_trace=/app/app.py L120 
[2025-03-23 22:39:30,441] INFO 172.22.0.1 - - [23/Mar/2025 22:39:30] "GET /goals/{goal_id}?goal_id=2 HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:39:32,303] INFO Retrieving saving goal with ID: 2 - call_trace=/app/app.py L107 
[2025-03-23 22:39:32,304] INFO Saving goal with ID 2 found - call_trace=/app/app.py L120 
[2025-03-23 22:39:32,305] INFO 172.22.0.1 - - [23/Mar/2025 22:39:32] "GET /goals/{goal_id}?goal_id=2 HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:39:33,088] INFO Retrieving saving goal with ID: 2 - call_trace=/app/app.py L107 
[2025-03-23 22:39:33,089] INFO Saving goal with ID 2 found - call_trace=/app/app.py L120 
[2025-03-23 22:39:33,090] INFO 172.22.0.1 - - [23/Mar/2025 22:39:33] "GET /goals/{goal_id}?goal_id=2 HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:40:54,227] INFO  * Detected change in '/app/schemas/saving_goal.py', reloading - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:40:54,378] INFO  * Restarting with stat - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:40:55,876] INFO Retrieving saving goal with ID: 2 - call_trace=/app/app.py L107 
[2025-03-23 22:40:55,881] INFO Saving goal with ID 2 found - call_trace=/app/app.py L120 
[2025-03-23 22:40:55,883] INFO 172.22.0.1 - - [23/Mar/2025 22:40:55] "GET /goals/{goal_id}?goal_id=2 HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:40:59,040] INFO Retrieving saving goal with ID: 2 - call_trace=/app/app.py L107 
[2025-03-23 22:40:59,041] INFO Saving goal with ID 2 found - call_trace=/app/app.py L120 
[2025-03-23 22:40:59,042] INFO 172.22.0.1 - - [23/Mar/2025 22:40:59] "GET /goals/{goal_id}?goal_id=2 HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:41:06,120] INFO Retrieving saving goal with ID: 2 - call_trace=/app/app.py L107 
[2025-03-23 22:41:06,121] INFO Saving goal with ID 2 found - call_trace=/app/app.py L120 
[2025-03-23 22:41:06,122] INFO 172.22.0.1 - - [23/Mar/2025 22:41:06] "GET /goals/{goal_id}?goal_id=2 HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:41:06,816] INFO Retrieving saving goal with ID: 2 - call_trace=/app/app.py L107 
[2025-03-23 22:41:06,817] INFO Saving goal with ID 2 found - call_trace=/app/app.py L120 
[2025-03-23 22:41:06,818] INFO 172.22.0.1 - - [23/Mar/2025 22:41:06] "GET /goals/{goal_id}?goal_id=2 HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:41:43,057] INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.22.0.2:5000 - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:41:43,058] INFO [33mPress CTRL+C to quit[0m - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:41:43,058] INFO  * Restarting with stat - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:41:49,354] INFO Retrieving saving goal with ID: 2 - call_trace=/app/app.py L107 
[2025-03-23 22:41:49,358] WARNING Saving goal with ID 2 not found. - call_trace=/app/app.py L117 
[2025-03-23 22:41:49,360] INFO 172.22.0.1 - - [23/Mar/2025 22:41:49] "[33mGET /goals/{goal_id}?goal_id=2 HTTP/1.1[0m" 404 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:41:51,651] INFO Retrieving saving goal with ID: 2 - call_trace=/app/app.py L107 
[2025-03-23 22:41:51,653] WARNING Saving goal with ID 2 not found. - call_trace=/app/app.py L117 
[2025-03-23 22:41:51,654] INFO 172.22.0.1 - - [23/Mar/2025 22:41:51] "[33mGET /goals/{goal_id}?goal_id=2 HTTP/1.1[0m" 404 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:42:07,645] INFO 172.22.0.1 - - [23/Mar/2025 22:42:07] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:42:07,679] INFO 172.22.0.1 - - [23/Mar/2025 22:42:07] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:42:41,238] INFO  * Restarting with stat - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
